# Generated by Django 5.2 on 2025-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodation_apartment_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='room_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
