# Generated by Django 5.2 on 2025-05-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_apartment_room_count_apartment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='apartements_count',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='accommodation.accommodation')),
            ],
        ),
    ]
