# Generated by Django 5.2 on 2025-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_remove_apartment_accommodation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='apartements_count',
        ),
    ]
