# Generated by Django 5.2 on 2025-05-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_remove_accommodation_apartements_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accommodation.block'),
        ),
    ]
