# Generated by Django 5.2 on 2025-05-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_alter_apartment_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='room_count',
        ),
    ]
