# Generated by Django 5.2 on 2025-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_remove_apartment_room_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(choices=[('deluxe', 'Deluxe'), ('premium', 'Premium')], default='premium', max_length=10),
        ),
    ]
