# Generated by Django 5.2 on 2025-05-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_remove_room_type_apartment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='issue',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='issue_type',
            field=models.CharField(choices=[('Water Leakage', 'Water Leakage'), ('Air Conditioner', 'Air Conditioner'), ('Electricity', 'Electricity'), ('Furniture', 'Furniture'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
