# Generated by Django 5.2 on 2025-05-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_remove_maintenancerequest_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
