# Generated by Django 5.2 on 2025-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0011_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('inactive', 'Inactive')], default='available', max_length=10),
        ),
    ]
